name: Push-to-EC2

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/st-app.pem
          chmod 400 ~/.ssh/st-app.pem

      - name: Deploy to Server
        run: |
          ssh -i ~/.ssh/st-app.pem ubuntu@${{ secrets.HOST_DNS }} 'bash -s' < deploy_aws_ec2.sh

      - name: Execute remote SSH commands
        run: |
          ssh -i ~/.ssh/st-app.pem ubuntu@${{ secrets.HOST_DNS }} 'bash -s' < execute_remote_commands.sh
