name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Adjust this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Deploy to AWS EC2
      run: |
        ssh -i "st-app.pem" ubuntu@ec2-3-80-246-189.compute-1.amazonaws.com
